### ISSUE TITLE
few spelling mistakes in early draft 

### ISSUE THREAD

**Issue by MartinH-open** [AlexandraKapp/blog#1]
Please review and fix a few spelling mistakes in early draft of "Human Mobility Data Use Case Collection" (as of now).
List of few words to reconsider:
continously 
marices 
cylclists
bumpyness
povide 
bicylce 
bicyle 
longterm 
reportings (=> reports ?)
start end end locations

**Comment by AlexandraKapp** [comment]
thanks!
